Add LDN/Tester reaction-roles select support in Ryujinx guild with Ryuko
Ryujinx/ryuko-ng pull request #9
Opened 2021-09-24 08:45 UTC by choppymaster

This allows users to select their ldn roles and tester role by reacting to a message sent by Ryuko in a channel which specially for this.
![Screenshot_2021-09-24-14-04-06-1](https://user-images.githubusercontent.com/74042715/134644516-ccae3729-86d6-43a4-a153-620f0ad6672a.png)
Users have to just unreact to the reaction to remove the role if needed.
- [ ]  Add logging maybe?
- [ ]  Improve embed description.
Refer: https://github.com/Ryujinx/Ryujinx/projects/5#card-53749923
Requesting to test this too.

2021-09-24 09:16 UTC, Pixxel123 commented on robocop_ng/cogs/ryujinx_reactionroles.py
> +            "🏎️": "Looking for LDN game (Mario Kart 8 Deluxe)",
I've noticed that the current role says `Looking for LDN game (Mario Kart 8)`, not Mario Kart 8 Deluxe. Is this an oversight?

![image](https://user-images.githubusercontent.com/36304206/134650433-c82c3da1-1357-4b28-b402-a4bd2870ebfc.png)

2021-09-24 09:25 UTC, Pixxel123 commented on robocop_ng/cogs/ryujinx_reactionroles.py
> +        self.file = "data/reactionroles.json"  # the file to store the required reaction role data. (message id of the RR message.)
Do we really need to make a .json file instead of just storing and accessing roles in a dict?

2021-09-24 11:35 UTC, choppymaster commented on robocop_ng/cogs/ryujinx_reactionroles.py
> +            "🏎️": "Looking for LDN game (Mario Kart 8 Deluxe)",
Thx

2021-09-24 11:44 UTC, choppymaster commented on robocop_ng/cogs/ryujinx_reactionroles.py
> +        self.file = "data/reactionroles.json"  # the file to store the required reaction role data. (message id of the RR message.)
The process of setup or RR is automatic
The bot will automatically setup all the things, sebding message, intially reacting to it, etc. The mesaage id is taking by the bot too. We have to only specify the channel id in config. So creating and storing in json is right.

2021-09-30 07:24 UTC, Thog requested changes

2021-09-30 07:24 UTC, Thog commented on start.sh
> +pip3 install -Ur requirements.txt
Remove this file

2021-09-30 07:24 UTC, Thog commented on robocop_ng/cogs/ryujinx_reactionroles.py
> +        self.emoji_map = {
imo this should be merged with the data in ``reactionroles.json`` and init when the file doesn't exist.

2021-09-30 07:24 UTC, Thog commented on robocop_ng/cogs/ryujinx_reactionroles.py
> +        )  # The channel to send the reaction role message. (self-roles channel)
comment should be put on its own line.

2021-09-30 07:24 UTC, Thog commented on robocop_ng/cogs/ryujinx_reactionroles.py
> +                )  # payload.member.remove_roles will throw error
comment should be put on its own line.

2021-09-30 07:24 UTC, Thog commented on robocop_ng/cogs/ryujinx_reactionroles.py
> +                    name=self.emoji_map[str(payload.emoji.name)],
```suggestion
                    name = self.emoji_map[str(payload.emoji.name)],
```

2021-09-30 08:19 UTC, choppymaster commented on robocop_ng/cogs/ryujinx_reactionroles.py
> +                )  # payload.member.remove_roles will throw error
Oh sorry its because of stupid `black` format

2021-09-30 08:49 UTC, choppymaster commented on robocop_ng/cogs/ryujinx_reactionroles.py
> +        self.emoji_map = {
I think this should be nice as the process is automatic and the code will much easy to instruct

2021-10-01 04:55 UTC, choppymaster commented on robocop_ng/cogs/ryujinx_reactionroles.py
> +                    name=self.emoji_map[str(payload.emoji.name)],
Its not a variable

2021-10-09 03:18 UTC, choppymaster commented
By accident.

2021-10-09 03:18 UTC, choppymaster commented
By accident.

2021-11-02 08:41 UTC, choppymaster commented
Pokemon Sword/Shield, and Mario Party Superstars roles are added.

2021-11-09 05:45 UTC, choppymaster commented
@Thog

2021-11-12 22:47 UTC, Thog approved these changes
lgtm

2021-11-14 01:17 UTC, choppymaster commented
Ok

2022-01-10 08:42 UTC, merged